### ISSUE TITLE
Critique <3

### ISSUE THREAD

**Issue by esbenkc** [KennethEnevoldsen/tutorial_fine-tuning_danish_bert#1]
## Super good tutorial! A couple of things:
- Would be good to see a clearer view of the output of the sentence classification
- It is unclear in the sentence classification that you're doing named-entity recognition
- Output simplified from the at red backgrounds - a table (?) and possibly explanation of content
  - E.g. example output in sentence classification would be nice to have a clear classified-as column
- A couple of flobbles (like renames instead of renamed)
- Very nice with the head(10) - good overview and no clutter
- Good structure with intro, data overview, model overview, usage example

**Comment by KennethEnevoldsen** [comment]
1. What do refer to? The models haven’t been trained as this takes as such there is No output to show 
2. I am not - named entire recognition is for token classification
3. Again the model’s isn’t trained - the training data for the NER is poor results and the is more to be done to structure data for the sentence classification (i.e. Training with the current training data would be a waste)
4. Will correct the renamed - are there Others?

Will add some trained examples one we have them

**Comment by esbenkc** [comment]
[2] I presumed that you wanted to use the model to classify the sentences to show an example. [1, 3] 👍
[4] 
- "this dataset contain a training dataset" [contains]
- "examing the first..." [examining]
- "not that the renames variable..." [note, renamed]
- "number og unique labels" [of]
- "start of by downloading" [off]
- "classyfying" [classifying]
Also a couple of grammar things as well
- "...o choose from, but we recommend..." [no comma]
- "If not download it from..." [not*,* download]
- "...as is for example..." [a bit unclear]
- "Okay so now..." [Okay*,* so]
 - "That is it you have..." [it*.* You]
